### ISSUE TITLE
have flake8 pass arguments to underlying cmd

### ISSUE THREAD

**Issue by yggdr** [pre-commit/pre-commit-hooks#146] opened 2016-10-22 18:38 UTC
I'm especially talking about the --ignore argument. Currently, the flake8 hook seems utterly unconfigurable.

**Comment by chriskuehl** [comment] 2016-10-22 18:48
This is definitely possible, can you provide more information on how you're trying to use it?


```
(tmp.G8UzOGTDTh) ckuehl@hydrogen:/tmp/tmp.1wPVsAtd2L$ cat .pre-commit-config.yaml
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: c8a1c91c762b8e24fdc5a33455ec10662f523328
    hooks:
    -   id: flake8
(tmp.G8UzOGTDTh) ckuehl@hydrogen:/tmp/tmp.1wPVsAtd2L$ cat test.py
x=3
(tmp.G8UzOGTDTh) ckuehl@hydrogen:/tmp/tmp.1wPVsAtd2L$ pre-commit run --files test.py
Flake8............................................................................Failed
hookid: flake8

test.py:1:2: E225 missing whitespace around operator
```

Then I add the line `args: ['--ignore=E225']` to my `.pre-commit-config.yaml`:
```
ckuehl@hydrogen:/tmp/tmp.1wPVsAtd2L$ cat .pre-commit-config.yaml
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: c8a1c91c762b8e24fdc5a33455ec10662f523328
    hooks:
    -   id: flake8
        args: ['--ignore=E225']

(tmp.G8UzOGTDTh) ckuehl@hydrogen:/tmp/tmp.1wPVsAtd2L$ pre-commit run --files test.py
Flake8............................................................................Passed
```

On a related note, you can also configure flake8 via a `tox.ini` file (this is usually what we recommend rather than passing arguments in `.pre-commit-config.yaml`).

**Comment by asottile** [comment] 2016-10-22 19:10
May also be a duplicate of https://github.com/pre-commit/pre-commit-hooks/issues/112 https://gitlab.com/pycqa/flake8/issues/10

**Comment by yggdr** [comment] 2016-10-22 20:36
I don't do much yaml, so I just adapted the examples on pre-commit.yaml. There the args-list is always seen without quotes around them, and a I somehow didn't think to try that while experimenting. Thanks and sorry for the noise.

**Comment by chriskuehl** [comment] 2016-10-22 20:58
Cool, glad you got it working! FWIW you actually don't need the quotes, though (this works too: `args: [--ignore=E225]`). I just think it looks silly (and leads to subtle problems when you use a bareword that isn't unambiguously a string) so I usually add quotes.

Let us know if you think the docs could be improved somehow.

**Closed by chriskuehl** 2016-10-22 20:58 UTC

**Comment by yggdr** [comment] 2016-10-22 22:33
Well, now I'm thoroughly confused:
`args: [--ignore="E501,E302,E261,E701,E241,E126,E127,E128,W801,W391,F401,F403"]`
gets ignored, but
`args: ['--ignore="E501,E302,E261,E701,E241,E126,E127,E128,W801,W391,F401,F403"']`
worked before, but now that I'm testing around, it suddenly does give me a F403 (which should've been ignored).
`args: ['--ignore=E501,E302o,E261,E701,E241,E126,E127,E128,W801,W391,F401,F403']`
works as expected, but
`args: [--ignore=E501,E302o,E261,E701,E241,E126,E127,E128,W801,W391,F401,F403]`
gives me an F401 and an F403?

**Comment by asottile** [comment] 2016-10-23 16:59
Mostly because yaml is dumb, here's why:

```python
>>> yaml.load('args: [--ignore="E501,E302,E261,E701,E241,E126,E127,E128,W801,W391,F401,F403"]')
{'args': ['--ignore="E501', 'E302', 'E261', 'E701', 'E241', 'E126', 'E127', 'E128', 'W801', 'W391', 'F401', 'F403"']}
>>> yaml.load('args: [\'--ignore="E501,E302,E261,E701,E241,E126,E127,E128,W801,W391,F401,F403"\']')
{'args': ['--ignore="E501,E302,E261,E701,E241,E126,E127,E128,W801,W391,F401,F403"']}
# The correct one, notice it doesn't end up with internal quotes or split arguments
>>> yaml.load("args: ['--ignore=E501,E302o,E261,E701,E241,E126,E127,E128,W801,W391,F401,F403']")
{'args': ['--ignore=E501,E302o,E261,E701,E241,E126,E127,E128,W801,W391,F401,F403']}
>>> yaml.load('args: [--ignore=E501,E302o,E261,E701,E241,E126,E127,E128,W801,W391,F401,F403]')
{'args': ['--ignore=E501', 'E302o', 'E261', 'E701', 'E241', 'E126', 'E127', 'E128', 'W801', 'W391', 'F401', 'F403']}
```

Yet another reason we're looking to factor out yaml: https://github.com/pre-commit/pre-commit/issues/414

**Comment by asottile** [comment] 2016-10-25 18:25
I believe you're looking for the `args` setting (also perhaps the `exclude`
option).  The documentation for using this is on
http://pre-commit.com
