### ISSUE TITLE
aws hook: error if credentials folder does not exist

### ISSUE THREAD

**Issue by manquer** [pre-commit/pre-commit-hooks#141] opened 2016-08-29 05:40 UTC
There is an error in aws hook if the credentials are not configured at all.

```
Detect AWS Credentials......................................................Failed
hookid: detect-aws-credentials
No aws keys were configured at ~/.aws/credentials
Configure them with --credentials-file
```
This should ideally pass/ only throw warning.

**Comment by asottile** [comment] 2016-08-29 09:25
It would silently fail forever. This is the only way you would ever know it is not configured. Closing as intentional :)

**Closed by asottile** 2016-08-29 09:25 UTC

**Comment by manquer** [comment] 2016-08-29 10:26
:) I have actually have two use cases for this 
a) aws credentials are not stored on my laptop however I occasionally do need to make commits from my laptop. 
b) not all of the team members who collaborate with me have access to aws credentials / or have only setup corresponding language sdks not the not CLI ( this is how we found the issue)

**Comment by arahayrabedian** [comment] 2016-08-29 10:38
hey @asottile I think this has some merit, but think something in the parent project to allow something like a soft-fail flag so that it's generic instead of implemented per-hook, what do you think?

**Comment by asottile** [comment] 2016-08-29 12:57
I believe you're looking for SKIP http://pre-commit.com

**Comment by arahayrabedian** [comment] 2016-08-29 13:04
I forgot about skip, that does work in a manual way for his case, but imagine being the poor bloke who happens not to have AWS Creds.

A dirty workaround @manquer may be a dummy credentials file somewhere on the machines which don't have credentials?

**Comment by asottile** [comment] 2016-08-29 13:38
I should elaborate (sent the last message as I was silencing my alarm).

We've considered a warning system in the past but it always had the
following problems:

## what if the warning is right?

It's too late, the push / commit has already happened.

Consider this hook:
- is using pre-push (for commit the problem is slightly less bad but still
requires local history rewriting)
- someone configures in ~/.boto instead
- accidentally commits creds
- warning fires in git push
- :(

## how does a hook communicate a warning

stdout / stderr don't really work since pre-commit combines them and treats
them as opaque bytes (this avoids the various encoding issues that the
hooks themselves may have)

return codes don't really work either since there's both no standard and
xargs gets involved

signals: not cross platform

## well it could be interactive

Currently pre-commit is entirely non interactive and I'd like to keep it
that way.  Reading input from the keyboard also poses issues for usage in
CI and personally I find prompts somewhat annoying. It'd also increase
warning fatigue especially if you have to answer a set of prompts every
time you commit.

## SKIP covered every use case for warnings we could think of

## opt-in vs opt-out

I've found that if you make a useful system that's opt in people are much
less likely to use it.  SKIP represents a (safer) opt out solution to the
problem

**Comment by asottile** [comment] 2016-08-29 13:40
For no aws creds you can permanently opt out with something like `echo
'export SKIP=...' >> ~/.profile`

**Comment by arahayrabedian** [comment] 2016-08-29 13:48
@asottile I do agree, I had forgotten about how skip works entirely, message was editted above to reflect as I remembered how it's used.

I actually assumed you don't sleep after seeing stuff on here at all times of the day and night :P

**Comment by asottile** [comment] 2016-08-29 14:31
heh, I sleep sometimes.  I was in europe for a while a couple weeks back which would explain those strange commenting times :D

**Comment by manquer** [comment] 2016-08-29 15:21
@asottile @arahayrabedian thx for suggesting SKIP, this should work for all scenarios. I agree the opt-out part of design is safer, perhaps adding this in the documentation would help users know what they can do.
