### ISSUE TITLE
yapf hook

### ISSUE THREAD

**Issue by guykisel** [pre-commit/pre-commit-hooks#50] opened 2015-03-25 15:56 UTC
https://github.com/google/yapf looks like a neat tool to potentially replace autopep8. It does appear to be a bit immature, but once it stabilizes I think it could make for a good hook.

**Comment by asottile** [comment] 2015-03-25 18:38
Looks cool! Hopefully it stabilizes :)

**Comment by jab** [comment] 2015-03-29 14:46
Would you consider adding a hook for yapf now?

**Comment by asottile** [comment] 2015-03-29 15:46
Sure! Would you like to take a stab at a PR or should I?

**Comment by jab** [comment] 2015-03-29 16:23
Awesome, thanks! I'm still trying to get `pre-commit run` to work for the first time (new user; it's failing with `FileNotFoundError: [Errno 2] No such file or directory: 'virtualenv'`), so if you're up for it, that'd be great. If I get past this I might take a stab if no one beats me to it though.

**Comment by asottile** [comment] 2015-03-29 16:31
ah yeah I actually just fixed that here: https://github.com/pre-commit/pre-commit/pull/216

Lemme merge that and bump the version

**Comment by asottile** [comment] 2015-03-29 16:34
That bug should be fixed with 0.4.4 of pre-commit

**Comment by jab** [comment] 2015-03-29 16:36
Nice, thanks!

**Comment by asottile** [comment] 2015-03-29 16:39
@jab if you see additional bugs like that, be sure to report them here: https://github.com/pre-commit/pre-commit/issues :D

**Comment by jab** [comment] 2015-03-29 16:46
Will do!

Meanwhile, will keep an eye on this ticket for yapf support.

Thanks for making this project, it's awesome!

**Comment by jab** [comment] 2015-03-30 18:57
@asottile I had a chance to start a PR for this in #51. Not ready to be merged yet but figured I'd create it now anyway to get the ball rolling. In particular, looking at the autopep8 wrapper as an example, I'm not sure if we can similarly call into yapf's arg parsing code to get individual files out of the `files` arg and format them one-by-one, since yapf creates the arg parser inside its `main` function. What do you recommend?

Also just noting a test should be added once that's working.

Feel free to move discussion over to #51 if that's a better place for it.

**Comment by struys** [comment] 2015-03-30 23:12
@jab can you just call the main in a loop? Pass in individual files and print if the return code is non-0

**Comment by jab** [comment] 2015-03-30 23:14
@struys The issue is we want to parse the individual files out of argv using yapf's arg parsing code before calling its `main`, but its arg parsing code is inside its `main`. Maybe they'd be amenable to factoring it out into its own function so it could be called separately as with autopep8, but for now that's not what they do.

**Comment by asottile** [comment] 2015-03-30 23:44
Might be worth poking them to see what they think.  Maybe they'd even support our interface and add a hooks.yaml file

**Comment by jab** [comment] 2015-03-30 23:59
@asottile That'd be great! If you want to do the poking as the project maintainer I'd be happy to +1 as a user and yapf contributor (reported some bugs that got acknowledged today).

**Comment by asottile** [comment] 2015-03-31 01:27
Pokeage: https://github.com/google/yapf/issues/57

**Comment by jab** [comment] 2015-03-31 01:34
Nice!

**Comment by guykisel** [comment] 2015-03-31 02:30
Cool!

**Comment by k1-hedayati** [comment] 2015-07-02 06:02
Great, I'm looking for this hook in pre-commit, hope your negotiations go well on yapf side :)

**Comment by asottile** [comment] 2015-12-02 18:27
With the lates version of pre-commit this'll work out of the box: https://github.com/pre-commit/mirrors-yapf

**Comment by guykisel** [comment] 2015-12-03 03:53
Nice!

**Closed** 2016-02-21 01:13 UTC
