### ISSUE TITLE
Switch to ruamel.yaml doesn't work in some environments (related to pipenv?)

### ISSUE THREAD

**Issue by isstabb** [pre-commit/pre-commit-hooks#353] opened 2019-01-04 20:46 UTC
I just started using pre-commit and pointed my default pre-commit-hooks to master (I wasn't really sure what rev to use.)  I didn't realize master was unreleased actually.  Once I switch the rev to `v2.0.0` I don't see this issue anymore.  Looking at the recent commits and the error message, it appears related to the switch to ruamel.yaml.  This is the error I'm seeing:

```
Don't commit to branch...................................................Failed
hookid: no-commit-to-branch

Traceback (most recent call last):
  File "/Users/me/.cache/pre-commit/repoMozTJN/py_env-python2.7/bin/no-commit-to-branch", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/me/.cache/pre-commit/repoMozTJN/py_env-python2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/Users/me/.cache/pre-commit/repoMozTJN/py_env-python2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/Users/me/.cache/pre-commit/repoMozTJN/py_env-python2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/me/.cache/pre-commit/repoMozTJN/py_env-python2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/Users/me/.cache/pre-commit/repoMozTJN/py_env-python2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/me/.cache/pre-commit/repoMozTJN/py_env-python2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ruamel.ordereddict' distribution was not found and is required by ruamel.yaml
```

The only thing of note I can think of is I installed pre-commit via pipenv.  Pipenv is using a clean 2.7.14 via pyenv.  If I look at that repo directory in the `.cache/pre-commit` I can see the links to my pipenv environment bins as expected.  Here's the listing of site-packages in there:

```
_ruamel_yaml.so
backports
configparser-3.5.0-py2.7-nspkg.pth
configparser-3.5.0-py2.7.egg-info
configparser.py
easy_install.py
easy_install.pyc
enum
enum34-1.1.6.dist-info
flake8
flake8-3.6.0.dist-info
mccabe-0.6.1.dist-info
mccabe.py
mccabe.pyc
pep8.py
pep8.pyc
pip
pip-6.0.8.dist-info
pkg_resources
pre_commit_hooks
pre_commit_hooks-2.1.0-py2.7.egg-info
pycodestyle-2.4.0.dist-info
pycodestyle.py
pycodestyle.pyc
pyflakes
pyflakes-2.0.0.dist-info
ruamel
ruamel.yaml-0.15.83-py2.7-nspkg.pth
ruamel.yaml-0.15.83-py2.7.egg-info
setuptools
setuptools-40.6.3.dist-info
six-1.12.0.dist-info
six.py
six.pyc
```

Not sure what else to upload to help.

**Comment by asottile** [comment] 2019-01-04 20:52
hmm! that is pretty odd -- can you provide `pre-commit --version` and `virtualenv --version`?

**Comment by isstabb** [comment] 2019-01-04 20:53
pre-commit 1.13.0 and 12.0.7 respectively. Thanks!

**Comment by asottile** [comment] 2019-01-04 20:56
upgrading virtualenv should work around it I think -- I'm able to reproduce with older virtualenv -- still trying to pin down a minimal reproduction

**Comment by asottile** [comment] 2019-01-04 21:03
Here's a minimal reproduction:

```bash
rm -rf venv setup.py x.py

virtualenv venv -ppython2.7
venv/bin/pip install 'pip<7'

cat > x.py << EOF
import ruamel.yaml
def main():
    pass
EOF

cat > setup.py << EOF
from setuptools import setup
setup(
    name="x",
    install_requires=["ruamel.yaml"],
    entry_points={"console_scripts": ["x=x:main"]},
    py_modules=["x"],
)
EOF

./venv/bin/pip install .
./venv/bin/x
```

```console
+ rm -rf venv setup.py x.py
+ virtualenv venv -ppython2.7
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /private/tmp/x/venv/bin/python
Installing setuptools, pip, wheel...done.
+ venv/bin/pip install 'pip<7'
Collecting pip<7
  Downloading https://files.pythonhosted.org/packages/67/f0/ba0fb41dbdbfc4aa3e0c16b40269aca6b9e3d59cacdb646218aa2e9b1d2c/pip-6.1.1-py2.py3-none-any.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 179kB/s 
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-6.1.1
+ cat
+ cat
+ ./venv/bin/pip install .
You are using pip version 6.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Processing /private/tmp/x
Collecting ruamel.yaml (from x==0.0.0)
  Using cached https://files.pythonhosted.org/packages/36/1e/56c8737386fdfaaea8ffb9ab994912d3d6a977ac1b87a2a8e3de5a398060/ruamel.yaml-0.15.83.tar.gz
Installing collected packages: ruamel.yaml, x
  Running setup.py install for ruamel.yaml
  Running setup.py install for x
Successfully installed ruamel.yaml-0.15.83 x-0.0.0
+ ./venv/bin/x
Traceback (most recent call last):
  File "./venv/bin/x", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/private/tmp/x/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/private/tmp/x/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/private/tmp/x/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/private/tmp/x/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/private/tmp/x/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/private/tmp/x/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ruamel.ordereddict' distribution was not found and is required by ruamel.yaml
```

I'll take this to the upstream

**Comment by isstabb** [comment] 2019-01-04 21:05
Thanks!  Can also confirm upgrading virtualenv worked.

**Comment by asottile** [comment] 2019-01-04 21:08
cool -- here's the upstream issue: https://bitbucket.org/ruamel/yaml/issues/270/cannot-install-using-pip-6x-python2x

since there isn't really anything we can do here, I'm going to close this -- thanks for the issue! 🎉

**Closed by asottile** 2019-01-04 21:08 UTC
